bases/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from bases.views import Home, HomeSinPrivilegios

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),

    path('logoaut/',auth_views.LogoutView.as_view(template_name='bases/login.html'),
        name='logout'),
    

    path('sin_privilegios/',HomeSinPrivilegios.as_view(), name='sin_privilegios'),
    ]

inv/urls.py
from django.urls import path

from .views import ProyectoView,ProyectoNew,ProyectoEdit, ProyectoDetalleEdit, ProyectoDetalleDel, ProyectoDel, \
     programa,PndView, PndNew, PndEdit, PndDel, DepartamentoView, DepartamentoNew, DepartamentoEdit, DepartamentoDel, \
     MunicipioView, MunicipioNew, MunicipioEdit, MunicipioDel, \
     PuebloView, PuebloNew, PuebloEdit, PuebloDel, \
     PoblacionView, PoblacionNew, PoblacionEdit, PoblacionDel, \
     ComunidadView, ComunidadNew, ComunidadEdit, ComunidadDel, dashboard, \
    ReporteComunidadExcel, DirectorioView
    
urlpatterns = [

    path('proyectos/', ProyectoView.as_view(), name='proyecto_list'),
    path('proyectos/new', ProyectoNew.as_view(), name='proyecto_new'),
    path('proyectos/edit/<int:pk>', ProyectoEdit.as_view(), name='proyecto_edit'),
    path('proyectos/delete/<int:pk>', ProyectoDel.as_view(), name='proyecto_del'),

    path('programas/edit/<int:programa_id>', programa, name='programas_edit'),
    path('programa/edit/<int:pk>', ProyectoDetalleEdit.as_view(), name='programas_detalle_edit'),
    path('programas/<int:programa_id>/delete/<int:pk>', ProyectoDetalleDel.as_view(), name='programas_del'),

   

    path('prioridades/', PndView.as_view(), name='pnd_list'), 
    path('prioridades/new', PndNew.as_view(), name='pnd_new'), 
    path('prioridades/edit/<int:pk>', PndEdit.as_view(), name='pnd_edit'),
    path('prioridades/delete/<int:pk>', PndDel.as_view(), name='pnd_del'),  

    path('departamentos/', DepartamentoView.as_view(), name='departamento_list'),
    path('departamentos/new', DepartamentoNew.as_view(), name='departamento_new'),
    path('departamentos/edit/<int:pk>', DepartamentoEdit.as_view(), name='departamento_edit'),
    path('departamentos/delete/<int:pk>', DepartamentoDel.as_view(), name='departamento_del'),

    path('municipios/', MunicipioView.as_view(), name='municipio_list'),
    path('municipios/new', MunicipioNew.as_view(), name='municipio_new'),
    path('municipios/edit/<int:pk>', MunicipioEdit.as_view(), name='municipio_edit'),
    path('municipios/delete/<int:pk>', MunicipioDel.as_view(), name='municipio_del'),

    path('pueblos/', PuebloView.as_view(), name='pueblo_list'),
    path('pueblos/new', PuebloNew.as_view(), name='pueblo_new'),
    path('pueblos/edit/<int:pk>', PuebloEdit.as_view(), name='pueblo_edit'),
    path('pueblos/delete/<int:pk>', PuebloDel.as_view(), name='pueblo_del'),
   
    path('poblacion/', PoblacionView.as_view(), name='poblacion_list'),
    path('poblacion/new', PoblacionNew.as_view(), name='poblacion_new'),
    path('poblacion/edit/<int:pk>', PoblacionEdit.as_view(), name='poblacion_edit'),
    path('poblacion/delete/<int:pk>', PoblacionDel.as_view(), name='poblacion_del'),

    
    

    #-----------------------------------------------------------------------------
    path('comunidades/', ComunidadView.as_view(), name='comunidad_list'),
    path('comunidades/new', ComunidadNew.as_view(), name='comunidad_new'),
    path('comunidades/edit/<int:pk>', ComunidadEdit.as_view(), name='comunidad_edit'),
    path('comunidades/delete/<int:pk>', ComunidadDel.as_view(), name='comunidad_del'),
    
    path('directorio/', DirectorioView.as_view(), name='directorio_list'),

    #Exportacion de archivos

    path('comunidad/reporte', ReporteComunidadExcel.as_view(), name='reporete_comunidad'),
    #path('dashboard/', Dashboard.as_view(), name='dashboard'),

    path('dashboard', dashboard, name='dashboard'),


    

]

sip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'),namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

inv/models.py
from django.db.models.signals import pre_save
from django.utils import timezone
from django.db import models
from bases.models import ClaseModelo


class Proyecto(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Nombre del proyecto', unique=True)
    contacto = models.CharField(max_length=100, help_text='Nombre del contacnto en territorio')
    telefono = models.CharField(max_length=16, help_text='Telefono')
    email = models.EmailField()
    donante = models.CharField(max_length=250, blank=True, null=True, help_text='Ente donante')
    fechaInicio = models.DateTimeField()
    fechaFin = models.DateTimeField()
    
    directa = 'DIRECTA'
    socio ='SOCIO'
    forma_ejecucion = [
        (directa,'DIRECTA'),
        (socio,'SOCIO'),
    ]
    ejecucion = models.CharField(
        max_length=7,
        choices=forma_ejecucion,
        default=directa
    )
    nombre_socio = models.CharField(max_length=250, help_text='Nombre del socio', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    
    def save(self, *args, **kwargs):
        self.descripcion = self.descripcion.upper()
        self.contacto = self.contacto.upper()
        if self.donante:
            self.donante = self.donante.upper()
            if self.nombre_socio:
                self.nombre_socio = self.nombre_socio.upper()
        super(Proyecto, self).save(*args, **kwargs)


class Meta:
    verbose_name_plural = "Proyectos"

# Función para actualizar el estado
def actualizar_estado_proyecto(sender, instance, **kwargs):
    ahora = timezone.now()
    if instance.fechaFin < ahora:
        instance.estado = False
    else:
        instance.estado = True
# Registra la señal
pre_save.connect(actualizar_estado_proyecto, sender=Proyecto)



class Pnd(ClaseModelo): 
    descripcion = models.CharField(max_length=100, help_text='Prioridad Nacional de Desarrollo', unique=True)
    def __str__(self):
        return'{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Pnd, self).save()
    
    class Meta:
        verbose_name_plural = "Prioridades "

class Departamento(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Nombre del departamento', unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Departamento, self).save()
    
    class Meta:
        verbose_name_plural = "Departamento"

class Municipio(ClaseModelo):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format( self.descripcion)
       

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Municipio, self).save()
    
    class Meta:
        verbose_name_plural = "Municipios"
        unique_together = ('departamento','descripcion')
        ordering = ['descripcion']

class Comunidad(ClaseModelo):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format( self.descripcion)
       

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Comunidad, self).save()
    
    class Meta:
        verbose_name_plural = "Comunidades"
        unique_together = ('municipio','descripcion')
        ordering = ['descripcion']

class Pueblo(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Pueblo, self).save()
    
    class Meta:
        verbose_name_plural = "Pueblos"
        ordering = ['descripcion']

        
class Poblacion(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Poblacion, self).save()
    
    class Meta:
        verbose_name_plural = "Poblaciones"
        ordering = ['descripcion']
        

class ProyectoDetalle(ClaseModelo):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100, help_text='Nombre del programa')
    objetivo = models.CharField(max_length=900, help_text='Objetivo')
    cantidad_beneficiados = models.IntegerField()
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    comunidad = models.ManyToManyField(Comunidad)
    pueblo = models.ForeignKey(Pueblo, on_delete=models.CASCADE, null=True, blank=True)
    poblacion = models.ForeignKey(Poblacion, on_delete=models.CASCADE)
    
    montoPND1 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND1 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND1 = models.CharField(max_length=500, blank=True, null=True)
    montoPND2 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND2 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND2 = models.CharField(max_length=500, blank=True, null=True)
    montoPND3 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND3 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND3 = models.CharField(max_length=500, blank=True, null=True)
    montoPND4 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND4 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND4 = models.CharField(max_length=500, blank=True, null=True)
    montoPND5 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND5 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND5 = models.CharField(max_length=500, blank=True, null=True)
    montoPND6 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND6 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND6 = models.CharField(max_length=500, blank=True, null=True)
    montoPND7 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND7 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND7 = models.CharField(max_length=500, blank=True, null=True)
    montoPND8 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND8 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND8 = models.CharField(max_length=500, blank=True, null=True)
    montoPND9 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND9 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND9 = models.CharField(max_length=500, blank=True, null=True)
    montoPND10 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND10 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND10 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro1 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro1 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro1 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro1 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro2 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro2 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro2 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro2 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro3 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro3 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro3 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro3 = models.CharField(max_length=500, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.descripcion = self.descripcion.upper()
        self.objetivo = self.objetivo.upper() if self.objetivo else None

        self.metaPND1 = self.metaPND1.upper() if self.metaPND1 else None
        self.indicadorPND1 = self.indicadorPND1.upper() if self.indicadorPND1 else None
        self.metaPND2 = self.metaPND2.upper() if self.metaPND2 else None
        self.indicadorPND2 = self.indicadorPND2.upper() if self.indicadorPND2 else None
        self.metaPND3 = self.metaPND3.upper() if self.metaPND3 else None
        self.indicadorPND3 = self.indicadorPND3.upper() if self.indicadorPND3 else None
        self.metaPND4 = self.metaPND4.upper() if self.metaPND4 else None
        self.indicadorPND4 = self.indicadorPND4.upper() if self.indicadorPND4 else None
        self.metaPND5 = self.metaPND5.upper() if self.metaPND5 else None
        self.indicadorPND5 = self.indicadorPND5.upper() if self.indicadorPND5 else None
        self.metaPND6 = self.metaPND6.upper() if self.metaPND6 else None
        self.indicadorPND6 = self.indicadorPND6.upper() if self.indicadorPND6 else None
        self.metaPND7 = self.metaPND7.upper() if self.metaPND7 else None
        self.indicadorPND7 = self.indicadorPND7.upper() if self.indicadorPND7 else None
        self.metaPND8 = self.metaPND8.upper() if self.metaPND8 else None
        self.indicadorPND8 = self.indicadorPND8.upper() if self.indicadorPND8 else None
        self.metaPND9 = self.metaPND9.upper() if self.metaPND9 else None
        self.indicadorPND9 = self.indicadorPND9.upper() if self.indicadorPND9 else None

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CDCI System</title>

  <!-- Custom fonts for this template-->
  <link href="{% static  'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  

 <!-- para graficas-->
 <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0/dist/chartjs-plugin-datalabels.min.js"></script>




  <!-- Custom styles for this template-->
  <link href="{% static  'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

   <!-- Custom styles for this page -->
   <link href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">

   <!-- jQuery Confirm -->
  <link rel="stylesheet" href="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.css' %}">

  <!-- XDSoft DateTimePicker -->  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />  

  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />
</head>

<body id="page-top" class="bg-gradient-primary">
  {% block side_bar %}
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'bases:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-sitemap"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> <sub>COOPERANTES</sub> </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      {% if perms.inv.view_comunidad %}

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li> 
      {% endif %}
      {% if perms.inv.view_proyecto %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:proyecto_list' %}">
          <i class="fa fa-sign-language"></i>
          <span>PROGRAMAS</span></a>
      </li>
      {% endif %}

      {% if perms.inv.view_pnd %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:pnd_list' %}">
          <i class="fa fa-cubes"></i>
          <span>PND</span></a>
      </li>
      {% endif %}

      {% if perms.inv.view_departamento %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:departamento_list' %}">
          <i class="fa fa-arrow-circle-right"></i>
          <span>Departamentos</span></a>
      </li>
      {% endif %}

      {% if perms.inv.view_municipio %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:municipio_list' %}">
          <i class="fa fa-chevron-circle-right"></i>
          <span>Municipios</span></a>
      </li>
      {% endif %}
      {% if perms.inv.view_comunidad %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:comunidad_list' %}">
          <i class="fa fa-chevron-circle-down"></i>
          <span>Comunidad</span></a>
      </li>
      {% endif %}


      {% if perms.inv.view_pueblo %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:pueblo_list' %}">
          <i class="fa fa-users"></i>
          <span>Pueblos</span></a>
      </li>
      {% endif %}

      {% if perms.inv.view_poblacion %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:poblacion_list' %}">
          <i class="fa fa-user-plus"></i>
          <span>Poblacion</span></a>
      </li>
      {% endif %}
      

      {% if perms.inv.view_comunidad %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inv:directorio_list' %}">
          <i class="fa fa-user-plus"></i>
          <span>Directorio</span></a>
      </li>
      
      {% endif %}
      


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    {% endblock side_bar %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% block top_bar %}
        <nav class="navbar bg-gradient-primary navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

       
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

           
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="mr-2 d-none d-lg-inline text-gray-400 ">{{ user.username }}</span>
                  <img class="img-profile rounded-circle" src="{% static 'base/img/undraw_profile.svg' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                   aria-labelledby="userDropdown">
                  <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">
                      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                      Salir
                  </a>
              </div>
          </li>

          </ul>

        </nav>
        {% endblock top_bar %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% block page_content %}
        <div class="container-fluid">
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
              <h1 class="h3 mb-0 text-gray-800"></h1>
          </div>
          <p style="text-align:center" class="h3 mb-0 text-gray-800"> </p>
          <div class="row justify-content-center">
              <div class="col-lg-6 text-center">
                  <img src="{% static 'base/img/logo.png' %}" alt="Imagen de fondo" style="max-width: 100%; height: auto;">
              </div>
          </div>
      </div>
      

        {% endblock %}
        <!-- /.container-fluid -->
        {% block footer %}

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span id="copyright"></span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  {% endblock %}
  <!-- End of Page Wrapper -->
  {% block login %} {% endblock %}
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">¿Cerrar Sesión para <mark> {{ user.username}} </mark>?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Al dar click en el botón Salir, cerrará la sesión para <mark> {{ user.username}} </mark>  </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="{% url 'bases:logout' %}">Salir</a>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="popup"></div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static  'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static  'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static  'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static  'base/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js'%}"></script>
  <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

   <script src="{% static 'base/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>


  <script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>
  <!-- borrar -->
  <script src="{% static 'base/vendor/Chart.js/chart.min.js' %}"></script>
  <script src="{% static 'base/js/demo/chart-bar-demo.js' %}"></script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>  

  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
  
  <script src="{% static  'base/js/jquery.chained.min.js' %}"></script>

  <script>

    $(document).ready(function () {
      jQuery.datetimepicker.setLocale('es');
    });


  </script>
    

  <script>
    
    
    function abrir_modal(url)
    {
      $("#popup").load(url, function(){
        $(this).modal({
          backdrop:'static',
          keyboard: false

        })
        $(thist).modal('show');
       
      });
      return false;

    }

    function cerrar_modal()
    {
      $('#popup').modal('hide');
      return false;
    }
    
    
    function mensaje(msg,color='green')
    {
      if (color=="success")
      {
        color="green";
      }
      if (color=="error")
      {
        color="red";
      }


      $.alert({
        title:'',
        theme:'material',
        type:color,
        content:msg
      });
    }

    {% if messages %}
      {% for message in messages %}
        //console.log("{{ message.tags }}");
        mensaje("{{ message }}","{{ message.tags }}");
      {% endfor %}
    {% endif %}


    
</script>

<script>
  const currentYear = new Date().getFullYear();
  const copyrightSpan = document.getElementById('copyright');
  copyrightSpan.textContent = `Copyright © AALD ${currentYear}`;
</script>
 
  {% block js_page %} {% endblock %}
</body>

</html>