inv/urls.py
from django.urls import path

from .views import ProyectoView,ProyectoNew,ProyectoEdit, ProyectoDetalleEdit, ProyectoDetalleDel, ProyectoDel, \
     programa,PndView, PndNew, PndEdit, PndDel, DepartamentoView, DepartamentoNew, DepartamentoEdit, DepartamentoDel, \
     MunicipioView, MunicipioNew, MunicipioEdit, MunicipioDel, \
     PuebloView, PuebloNew, PuebloEdit, PuebloDel, \
     PoblacionView, PoblacionNew, PoblacionEdit, PoblacionDel, \
     ComunidadView, ComunidadNew, ComunidadEdit, ComunidadDel, dashboard, \
    ReporteComunidadExcel, DirectorioView
    
urlpatterns = [

    path('proyectos/', ProyectoView.as_view(), name='proyecto_list'),
    path('proyectos/new', ProyectoNew.as_view(), name='proyecto_new'),
    path('proyectos/edit/<int:pk>', ProyectoEdit.as_view(), name='proyecto_edit'),
    path('proyectos/delete/<int:pk>', ProyectoDel.as_view(), name='proyecto_del'),

    path('programas/edit/<int:programa_id>', programa, name='programas_edit'),
    path('programa/edit/<int:pk>', ProyectoDetalleEdit.as_view(), name='programas_detalle_edit'),
    path('programas/<int:programa_id>/delete/<int:pk>', ProyectoDetalleDel.as_view(), name='programas_del'),

   

    path('prioridades/', PndView.as_view(), name='pnd_list'), 
    path('prioridades/new', PndNew.as_view(), name='pnd_new'), 
    path('prioridades/edit/<int:pk>', PndEdit.as_view(), name='pnd_edit'),
    path('prioridades/delete/<int:pk>', PndDel.as_view(), name='pnd_del'),  

    path('departamentos/', DepartamentoView.as_view(), name='departamento_list'),
    path('departamentos/new', DepartamentoNew.as_view(), name='departamento_new'),
    path('departamentos/edit/<int:pk>', DepartamentoEdit.as_view(), name='departamento_edit'),
    path('departamentos/delete/<int:pk>', DepartamentoDel.as_view(), name='departamento_del'),

    path('municipios/', MunicipioView.as_view(), name='municipio_list'),
    path('municipios/new', MunicipioNew.as_view(), name='municipio_new'),
    path('municipios/edit/<int:pk>', MunicipioEdit.as_view(), name='municipio_edit'),
    path('municipios/delete/<int:pk>', MunicipioDel.as_view(), name='municipio_del'),

    path('pueblos/', PuebloView.as_view(), name='pueblo_list'),
    path('pueblos/new', PuebloNew.as_view(), name='pueblo_new'),
    path('pueblos/edit/<int:pk>', PuebloEdit.as_view(), name='pueblo_edit'),
    path('pueblos/delete/<int:pk>', PuebloDel.as_view(), name='pueblo_del'),
   
    path('poblacion/', PoblacionView.as_view(), name='poblacion_list'),
    path('poblacion/new', PoblacionNew.as_view(), name='poblacion_new'),
    path('poblacion/edit/<int:pk>', PoblacionEdit.as_view(), name='poblacion_edit'),
    path('poblacion/delete/<int:pk>', PoblacionDel.as_view(), name='poblacion_del'),

    
    

    #-----------------------------------------------------------------------------
    path('comunidades/', ComunidadView.as_view(), name='comunidad_list'),
    path('comunidades/new', ComunidadNew.as_view(), name='comunidad_new'),
    path('comunidades/edit/<int:pk>', ComunidadEdit.as_view(), name='comunidad_edit'),
    path('comunidades/delete/<int:pk>', ComunidadDel.as_view(), name='comunidad_del'),
    
    path('directorio/', DirectorioView.as_view(), name='directorio_list'),

    #Exportacion de archivos

    path('comunidad/reporte', ReporteComunidadExcel.as_view(), name='reporete_comunidad'),
    #path('dashboard/', Dashboard.as_view(), name='dashboard'),

    path('dashboard', dashboard, name='dashboard'),


    

]

sip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'),namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

bases/models.py
from django.db import models

from django.contrib.auth.models import User


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True
        

inv/models.py
from django.db.models.signals import pre_save
from django.utils import timezone
from django.db import models
from bases.models import ClaseModelo


class Proyecto(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Nombre del proyecto', unique=True)
    contacto = models.CharField(max_length=100, help_text='Nombre del contacnto en territorio')
    telefono = models.CharField(max_length=16, help_text='Telefono')
    email = models.EmailField()
    donante = models.CharField(max_length=250, blank=True, null=True, help_text='Ente donante')
    fechaInicio = models.DateTimeField()
    fechaFin = models.DateTimeField()
    
    directa = 'DIRECTA'
    socio ='SOCIO'
    forma_ejecucion = [
        (directa,'DIRECTA'),
        (socio,'SOCIO'),
    ]
    ejecucion = models.CharField(
        max_length=7,
        choices=forma_ejecucion,
        default=directa
    )
    nombre_socio = models.CharField(max_length=250, help_text='Nombre del socio', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    
    def save(self, *args, **kwargs):
        self.descripcion = self.descripcion.upper()
        self.contacto = self.contacto.upper()
        if self.donante:
            self.donante = self.donante.upper()
            if self.nombre_socio:
                self.nombre_socio = self.nombre_socio.upper()
        super(Proyecto, self).save(*args, **kwargs)


class Meta:
    verbose_name_plural = "Proyectos"

# Función para actualizar el estado
def actualizar_estado_proyecto(sender, instance, **kwargs):
    ahora = timezone.now()
    if instance.fechaFin < ahora:
        instance.estado = False
    else:
        instance.estado = True
# Registra la señal
pre_save.connect(actualizar_estado_proyecto, sender=Proyecto)



class Pnd(ClaseModelo): 
    descripcion = models.CharField(max_length=100, help_text='Prioridad Nacional de Desarrollo', unique=True)
    def __str__(self):
        return'{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Pnd, self).save()
    
    class Meta:
        verbose_name_plural = "Prioridades "

class Departamento(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Nombre del departamento', unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Departamento, self).save()
    
    class Meta:
        verbose_name_plural = "Departamento"

class Municipio(ClaseModelo):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format( self.descripcion)
       

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Municipio, self).save()
    
    class Meta:
        verbose_name_plural = "Municipios"
        unique_together = ('departamento','descripcion')
        ordering = ['descripcion']

class Comunidad(ClaseModelo):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format( self.descripcion)
       

    def save(self):
        self.descripcion = self.descripcion.upper()#Pone en mayusculas la cadena de tedxto ingresada
        super(Comunidad, self).save()
    
    class Meta:
        verbose_name_plural = "Comunidades"
        unique_together = ('municipio','descripcion')
        ordering = ['descripcion']

class Pueblo(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Pueblo, self).save()
    
    class Meta:
        verbose_name_plural = "Pueblos"
        ordering = ['descripcion']

        
class Poblacion(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Poblacion, self).save()
    
    class Meta:
        verbose_name_plural = "Poblaciones"
        ordering = ['descripcion']
        

class ProyectoDetalle(ClaseModelo):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100, help_text='Nombre del programa')
    objetivo = models.CharField(max_length=900, help_text='Objetivo')
    cantidad_beneficiados = models.IntegerField()
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    comunidad = models.ManyToManyField(Comunidad)
    pueblo = models.ForeignKey(Pueblo, on_delete=models.CASCADE, null=True, blank=True)
    poblacion = models.ForeignKey(Poblacion, on_delete=models.CASCADE)
    
    montoPND1 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND1 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND1 = models.CharField(max_length=500, blank=True, null=True)
    montoPND2 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND2 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND2 = models.CharField(max_length=500, blank=True, null=True)
    montoPND3 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND3 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND3 = models.CharField(max_length=500, blank=True, null=True)
    montoPND4 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND4 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND4 = models.CharField(max_length=500, blank=True, null=True)
    montoPND5 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND5 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND5 = models.CharField(max_length=500, blank=True, null=True)
    montoPND6 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND6 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND6 = models.CharField(max_length=500, blank=True, null=True)
    montoPND7 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND7 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND7 = models.CharField(max_length=500, blank=True, null=True)
    montoPND8 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND8 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND8 = models.CharField(max_length=500, blank=True, null=True)
    montoPND9 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND9 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND9 = models.CharField(max_length=500, blank=True, null=True)
    montoPND10 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaPND10 = models.CharField(max_length=500, blank=True, null=True)
    indicadorPND10 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro1 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro1 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro1 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro1 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro2 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro2 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro2 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro2 = models.CharField(max_length=500, blank=True, null=True)

    PNDOtro3 = models.CharField(max_length=500, blank=True, null=True)
    montoOtro3 = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    metaOtro3 = models.CharField(max_length=500, blank=True, null=True)
    indicadorOtro3 = models.CharField(max_length=500, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.descripcion = self.descripcion.upper()
        self.objetivo = self.objetivo.upper() if self.objetivo else None

        self.metaPND1 = self.metaPND1.upper() if self.metaPND1 else None
        self.indicadorPND1 = self.indicadorPND1.upper() if self.indicadorPND1 else None
        self.metaPND2 = self.metaPND2.upper() if self.metaPND2 else None
        self.indicadorPND2 = self.indicadorPND2.upper() if self.indicadorPND2 else None
        self.metaPND3 = self.metaPND3.upper() if self.metaPND3 else None
        self.indicadorPND3 = self.indicadorPND3.upper() if self.indicadorPND3 else None
        self.metaPND4 = self.metaPND4.upper() if self.metaPND4 else None
        self.indicadorPND4 = self.indicadorPND4.upper() if self.indicadorPND4 else None
        self.metaPND5 = self.metaPND5.upper() if self.metaPND5 else None
        self.indicadorPND5 = self.indicadorPND5.upper() if self.indicadorPND5 else None
        self.metaPND6 = self.metaPND6.upper() if self.metaPND6 else None
        self.indicadorPND6 = self.indicadorPND6.upper() if self.indicadorPND6 else None
        self.metaPND7 = self.metaPND7.upper() if self.metaPND7 else None
        self.indicadorPND7 = self.indicadorPND7.upper() if self.indicadorPND7 else None
        self.metaPND8 = self.metaPND8.upper() if self.metaPND8 else None
        self.indicadorPND8 = self.indicadorPND8.upper() if self.indicadorPND8 else None
        self.metaPND9 = self.metaPND9.upper() if self.metaPND9 else None
        self.indicadorPND9 = self.indicadorPND9.upper() if self.indicadorPND9 else None

inv/templates/inv/comunidad_form.html
{% extends 'base/base.html' %}
{% block page_content %}

<div class="container">
    {% if obj %}
    <form method="POST" role="form" class="form-inline" action="" >
    {% else %}
    <form method="POST" role="form" class="form-inline" action="{% url 'inv:comunidad_new' %}" >
    {% endif %}
        <div class="col-xl-12 col-md-12 mb-12">
            {% if obj %}
            <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
            {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Comunidad
                    </div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-auto">
                                <div class="col-auto">Departamento</div>
                                <div class="col-auto">
                                    <select name="departamento" id="id_departamento" class="form-control from-control-sm" required>
                                        <option value="0">Seleccione</option>
                                        {% for item in departamentos %}
                                        <option value="{{item.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                    
                                </div>
                            </div>  
                            <div class="col-auto">
                                <div class="col-auto">Municipio</div>
                                <div class="col-auto">
                                    <select name="municipio" id="id_municipio" class="form-control from-control-sm" required>
                                        <option value="0">Seleccione</option>
                                        {% for item in municipios %}
                                        <option value="{{item.id}}" data-chained="{{item.departamento.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                    
                                </div>
                            </div>  

                            <div class="col-auto">
                                <div class="col-auto">Descripcion</div>
                                <div class="col-auto">
                                    {{ form.descripcion }}
                                    
                                </div>
                            </div>                           
                             
                            <div class="col-auto">
                                <div class="input-group">
                                    <label for="id_estado">Estado</label>
                                    {{ form.estado }}
                                </div>
                            </div>                    
                        </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'inv:comunidad_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                </div>
                </div>
            </div>
            </div>
        </div>
    </form>     
</div>
{% endblock page_content %}

{% block js_page %}

<script>
    $(function(){
        $("#id_departamento").val("{{ obj.municipio.departamento.id }}").change();
        $("#id_municipio").val("{{ obj.municipio.id }}").change();
        $("#id_municipio").chained("#id_departamento");
    });
</script>

{% if form.errors %}
<script>
    Swal.fire({
        title: 'Error!',
        text: 'Una comunidad con este nombre ya existe para este municipio.',
        icon: 'error',
    });
</script>
{% endif %}

{% endblock js_page %}

    

inv/templates/inv/departamento_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Departamentos {{obj.count}} </h6>
      
      {% if perms.inv.add_departamento %} 
      <a class="btn btn-primary" href="{% url 'inv:departamento_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
      {% endif %}
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Departamentos</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Numero</th>
              <th>Departamento</th>
              <th>Estado</th>
              <th>F. Creado</th>
              <th>F. Modif.</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <td>
                    {% if perms.inv.change_departamento %}
                  <a class="btn btn-warning btn-circle" href="{% url 'inv:departamento_edit' item.id %}"><i class="far fa-edit"></i></a>
                  {% endif %}
                  {% if perms.inv.delete_departamento %}
                  <a class="btn btn-danger btn-circle" href="{% url 'inv:departamento_del' item.id %}"><i class="fas fa-trash-alt"></i></a>
                  
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}
{% block js_page %}
<script>
  $("#sidebarToggle").click();
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}

inv/templates/inv/pnd_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Prioridades Nacionales de Desarrollo {{obj.count}} </h6>
      
      {% if perms.inv.add_comunidad %} 
      <a class="btn btn-primary" href="{% url 'inv:pnd_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
      {% endif %}
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Prioridades</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
               
              <th>No.</th>
              <th>PND</th>
              <th>Estado</th>
              <th>Creado</th>


              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ item.descripcion}}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
      
                  <td>
                    {% if perms.inv.change_proyecto %}
                  <a class="btn btn-warning btn-circle" href="{% url 'inv:pnd_edit' item.id %}"><i class="far fa-edit"></i></a>
                  {% endif %}
                  {% if perms.inv.delete_proyecto %}
                  <a class="btn btn-danger btn-circle" href="{% url 'inv:pnd_del' item.id %}"><i class="fas fa-trash-alt"></i></a>
                  {% endif %}
                  
                 
                  
                </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}
{% block js_page %}
<script>
  $("#sidebarToggle").click();
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}

inv/templates/inv/poblacion_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Poblaciones {{obj.count}} </h6>
      {% if perms.inv.add_poblacion %} 
      <a class="btn btn-primary" href="{% url 'inv:poblacion_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
      {% endif %}
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Poblaciones</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
               
              <th>No.</th>
              <th>Poblacion</th>
              <th>Estado</th>
              <th>Creado</th>


              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ item.descripcion}}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
      
                  <td>
                    {% if perms.inv.change_poblacion %}
                  <a class="btn btn-warning btn-circle" href="{% url 'inv:poblacion_edit' item.id %}"><i class="far fa-edit"></i></a>
                  {% endif %}
                  {% if perms.inv.delete_poblacion %}
                  <a class="btn btn-danger btn-circle" href="{% url 'inv:poblacion_del' item.id %}"><i class="fas fa-trash-alt"></i></a>
                  {% endif %}
                  
                 
                  
                </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}
{% block js_page %}
<script>
  $("#sidebarToggle").click();
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}

inv/templates/inv/proyecto_det_del.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'inv:programas_del' obj.proyecto.id obj.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Eliminar Programa
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            ¿Eliminar {{ obj.descripcion }} ?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

inv/templates/inv/pueblo_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Pueblos {{obj.count}} </h6>
      {% if perms.inv.add_pueblo %} 
      <a class="btn btn-primary" href="{% url 'inv:pueblo_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
      {% endif %}
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Pueblos</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
               
              <th>No.</th>
              <th>Pueblo</th>
              <th>Estado</th>
              <th>Creado</th>


              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ item.descripcion}}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
      
                  <td>
                    {% if perms.inv.change_pueblo %}
                  <a class="btn btn-warning btn-circle" href="{% url 'inv:pueblo_edit' item.id %}"><i class="far fa-edit"></i></a>
                  {% endif %}
                  {% if perms.inv.delete_pueblo %}
                  <a class="btn btn-danger btn-circle" href="{% url 'inv:pueblo_del' item.id %}"><i class="fas fa-trash-alt"></i></a>
                  {% endif %}
                  
                 
                  
                </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}
{% block js_page %}
<script>
  $("#sidebarToggle").click();
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}